version: '3.8'

services:
  postgres-db:
    image: postgres:15
    container_name: nest_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nestdb
    ports:
      - '5434:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
 
volumes:
  pgdata:
